# Differentiation Products

In [162]:
import numpy as np
q = np.array([0.4,0.4,0.1,0.1])
p = np.array([0.6 , 0.56, 0.88, 0.87])
α = np.array([-1.0, -1.1, -1.2, -1.3]) 
β = 0.5
# slope of own-demand curve: dqdp = α, firms prefer larger α (or smaller in magnitude)

def D(p):
    return 1+α*p

def P(q):
    return 1+α*q

P(q)

array([0.6 , 0.56, 0.88, 0.87])

In [163]:
def AvgP(p,q):
    return np.mean(p*q/np.sum(q))
    
AvgP(p,q)

0.15975

In [164]:
def D(p):
    return 1-p

def demand_derivatives(p, α, β):
    N = p.shape[0]
    dqdp = β * np.ones((N,N))
    np.fill_diagonal(dqdp, α)
    return dqdp

dqdp = demand_derivatives(p, α, β)
dqdp # no substitution

array([[-1. ,  0.5,  0.5,  0.5],
       [ 0.5, -1.1,  0.5,  0.5],
       [ 0.5,  0.5, -1.2,  0.5],
       [ 0.5,  0.5,  0.5, -1.3]])

In [165]:
def ownershipMatrix(p2f):
    J = len(p2f)
    F = len(np.unique(p2f))
    Ω = np.zeros((J,J))
    for i in range(J):
        for j in range(J):
            if p2f[i] == p2f[j]:
                Ω[i,j] = 1
    return Ω 

p2f = np.array([0,1,2,3])
Ω = ownershipMatrix(p2f)
Ω 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [166]:
def get_hhi(q,p2f):
    return np.sum(np.bincount(p2f, weights=q/np.sum(q))**2)

get_hhi(q, p2f)

0.3400000000000001

In [167]:
def get_mc(p, q, dqdp):
    return p + np.dot(np.linalg.inv(Ω*dqdp.T),q)

c = get_mc(p, q, dqdp)
c

array([0.2       , 0.19636364, 0.79666667, 0.79307692])

In [168]:
def foc(p,c,α,β,Ω):
    q = D(p)
    dqdp = demand_derivatives(p, α, β)
    FOC = -p + c - np.dot(np.linalg.inv(Ω*dqdp.T),q)
    return np.round(FOC,4)
foc(p,c,α,β,Ω)

array([0.    , 0.0364, 0.0167, 0.0231])

In [169]:
AvgP(p,q), get_hhi(q, p2f)

(0.15975, 0.3400000000000001)

In [170]:
def effectiveHHI(p, q, α, β, p2f):
    dqdp = demand_derivatives(p, α, β)
    Ω = ownershipMatrix(p2f)
    c = get_mc(p, q, dqdp)
    
    
    

SyntaxError: expected ':' (830766313.py, line 1)

# Mergers between Leaders

In [146]:
p2f_new = np.array([0,0,1,2])
Ω_new = ownershipMatrix(p2f_new)
Ω_new

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [147]:
import scipy as sp
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(c,α,β,Ω_new))
p_new 
q_new = D(p_new) 

In [148]:
p_new, q_new

(array([0.72703351, 0.70451636, 0.88907737, 0.88302793]),
 array([0.27296649, 0.29548364, 0.11092263, 0.11697207]))

In [149]:
AvgP(p_new,q_new), get_hhi(q_new, p2f_new) # Average Prices same. HHI rises.

(0.1910407477885206, 0.5505220282983005)

# Mergers between laggards

In [150]:
p2f_new = np.array([0,1,2,2])
Ω_new = ownershipMatrix(p2f_new)
Ω_new

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [151]:
import scipy as sp
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(c,α,β,Ω_new))
p_new 
q_new = D(p_new) 

In [152]:
p_new, q_new

(array([0.60000444, 0.57906102, 0.91542254, 0.90884376]),
 array([0.39999556, 0.42093898, 0.08457746, 0.09115624]))

In [153]:
AvgP(p_new,q_new), get_hhi(q_new, p2f_new) # Average Prices same. HHI rises.

(0.16154306340148014, 0.37053334995879417)

# Cost Increases

- avg.prices always rise
- low cost firm face cost increase: HHI falls because extremal quantitiy falls
- high cost firm face cost increase: HHI rises because avg quantities diverge from extremal values

In [158]:
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(c+np.array([0.1,0.1,0,0]),α,β,Ω))
q_new = D(p_new) 
p_new, q_new # prices rise, quantities fall
AvgP(p_new,q_new), get_hhi(q_new, p2f) # Average Price rises. HHI rises.

(0.174896438130207, 0.3174134154130151)

In [159]:
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(c+np.array([0,0,0.1,0.1]),α,β,Ω))
q_new = D(p_new) 
p_new, q_new # prices rise, quantities fall
AvgP(p_new,q_new), get_hhi(q_new, p2f) # Average Price rises. HHI rises.

(0.15827980960910001, 0.3912146751163883)

# Elasticity (price-sensitivity) falls
- |α| is increasing (i.e. it is away from 0, i.e more elastic. Consumers are increasingly price sensitive)
- Price-sensitivity rises for leading firm: avg prices fall as leading firm has to reduce prices,raise quantities --> avg prices fall, HHI rises
- Price-sensitivity falls for leading firm: avg prices rise as leading firm can raise prices,reduce quantities --> avg prices rise, HHI falls 
- Price-sensitivity rises for laggard firm: avg prices fall as laggard firms must reduce prices,raise quantities --> avg prices fall, HHI falls
- Price-sensitivity falls for laggard firm: avg prices rise as leading firm can raise prices,reduce quantities --> avg prices rise, HHI rises 


In [160]:
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(np.array([0.3,0.3,0.3,0.3]),
                                                              np.array([-1,-1.2,-1.4,-1.6]),β,Ω))
q_new = D(p_new) 
print(AvgP(p_new,q_new), get_hhi(q_new, p2f))
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(np.array([0.3,0.3,0.3,0.3]),
                                                              np.array([-1.1,-1.2,-1.4,-1.6]),β,Ω))
q_new = D(p_new) 
print(AvgP(p_new,q_new), get_hhi(q_new, p2f))
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(np.array([0.3,0.3,0.3,0.3]),
                                                              np.array([-0.9,-1.2,-1.4,-1.6]),β,Ω))
q_new = D(p_new) 
print(AvgP(p_new,q_new), get_hhi(q_new, p2f))

0.15123930568877716 0.2514731157668921
0.150394304619129 0.2509607479965958
0.15209326998505684 0.2522664289574993


In [161]:
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(np.array([0.3,0.3,0.3,0.3]),
                                                              np.array([-1,-1.2,-1.4,-1.6]),β,Ω))
q_new = D(p_new) 
print(AvgP(p_new,q_new), get_hhi(q_new, p2f))
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(np.array([0.3,0.3,0.3,0.3]),
                                                              np.array([-1.0,-1.2,-1.4,-1.7]),β,Ω))
q_new = D(p_new) 
print(AvgP(p_new,q_new), get_hhi(q_new, p2f))
p_new = sp.optimize.fsolve(foc, x0=np.array([0,0,0,0]), args=(np.array([0.3,0.3,0.3,0.3]),
                                                              np.array([-1.0,-1.2,-1.4,-1.5]),β,Ω))
q_new = D(p_new) 
print(AvgP(p_new,q_new), get_hhi(q_new, p2f))

0.15123930568877716 0.2514731157668921
0.15048754442105788 0.25178741902049545
0.15202721290815108 0.2511918819057559
